export const FETCH_POPULAR_MOVIES_REQUEST = 'FETCH_POPULAR_MOVIES_REQUEST'
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS'
export const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE'

export const FETCH_TOP_RATED_MOVIES_REQUEST = 'FETCH_TOP_RATED_MOVIES_REQUEST'
export const FETCH_TOP_RATED_MOVIES_SUCCESS = 'FETCH_TOP_RATED_MOVIES_SUCCESS'
export const FETCH_TOP_RATED_MOVIES_FAILURE = 'FETCH_TOP_RATED_MOVIES_FAILURE'

export const FETCH_UPCOMING_MOVIES_REQUEST = 'FETCH_UPCOMING_MOVIES_REQUEST'
export const FETCH_UPCOMING_MOVIES_SUCCESS = 'FETCH_UPCOMING_MOVIES_SUCCESS'
export const FETCH_UPCOMING_MOVIES_FAILURE = 'FETCH_UPCOMING_MOVIES_FAILURE'

export const FETCH_CURRENT_MOVIE_REQUEST = 'FETCH_CURRENT_MOVIE_REQUEST'
export const FETCH_CURRENT_MOVIE_SUCCESS = 'FETCH_CURRENT_MOVIE_SUCCESS'
export const FETCH_CURRENT_MOVIE_FAILURE = 'FETCH_CURRENT_MOVIE_FAILURE'